server:
  port: 8084
  
management:
  endpoint:
    health:
      probes:
        enabled: true
      
spring:
  data:
    mongodb:
      host: localhost
      port: 27017            
      authentication-database: admin
      database: configuration
      username: root
      password: q8SFbdesFv

# using ingress
#spring:
#  elasticsearch:
#    host: minikube.io
#    port: 443
#    pathPrefix: /mongodb/
#    verifyHostnames: false
#    validateCertificates: false
#    authentication-database: admin    
#    database: configuration
#    username: root
#    password: password

kube:
  url: https://172.23.0.2:8443
  
organization:
  host: localhost
  port: 8082
              
---
server:
  port: 8084
  
management:
  endpoint:
    health:     
      probes:
        enabled: true
          
spring:
  config:
    activate:
      on-profile: avib
  data:
    mongodb:
      host: avib-mongodb
      port: 27017
      authentication-database: admin
      database: configuration
      username: root
      password: password
      
organization:
  host: uniovi-avib-morphingprojections-backend-organization
  port: 8082      